version: "3.8"
services:
  backend:
    container_name: golang_backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
  frontend:
    container_name: sveltekit_app
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      - backend
    volumes:
      - ./frontend/:/frontend
      - /cards-fork/frontend/node_modules