version: "3.8"
services:
  database:
    container_name: pocketbase
    build:
      context: ./database
    ports:
      - 8080:8080
    volumes:
      - pocketbase:/data
  

  backend:
    container_name: golang_backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database


  frontend:
    container_name: sveltekit_app
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
      - database

volumes:
  pocketbase: