version: "3.8"
services:
  frontend:
    container_name: sveltekit_app
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend/:/frontend
      - /cards-fork/frontend/node_modules